# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 22713b8f5a25344f5e83ed5fbe5e46ba8ccdeb7c5bf1d34f4f4b058e72d824443585500d82e195cda9fb0d992cbc50abd2263d17555dbaa160461c1d7146acec

test:
  secret_key_base: ac0b52e79affe324a1d4b6fbd5a3fecde4aace429a39b65e9fc1e2ba4862423ae11cec4cd27ccb12aecf594b108eae5045ae10237392efb9feb8883d9967a52a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
